# Generated by Django 4.2.3 on 2023-07-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("veggie", "0004_receipe_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="recipe_view_count",
            field=models.IntegerField(default=1),
        ),
    ]
