# Generated by Django 4.2.3 on 2023-07-07 08:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("veggie", "0006_department_studentid_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="department",
        ),
        migrations.RemoveField(
            model_name="student",
            name="student_id",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.DeleteModel(
            name="StudentID",
        ),
    ]
